title: June Bible Reading Plan
description: Daily Scripture with Calendar and Links
theme: null
baseurl: ""
url: "https://github.com/scottsun2020/bible-reading-plan"

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]
