title: June Bible Reading Plan
description: Daily Scripture with Calendar and Links
theme: null
baseurl: ""
url: "https://scottsun2020.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]
